using Week3Project.Data.Entities;
using Week3Project.Data;
using Microsoft.EntityFrameworkCore;
using Serilog;
using Week3Project.Data.Enum;

namespace Week3Project.Api.Seeder;

public class Seeder : ISeeder
{
    // Factory utilized to isolate database context instances during heavy data-generation operations
    private readonly IDbContextFactory<StoreDbContext> _dbContextFactory;
    
    public Seeder(IDbContextFactory<StoreDbContext> factory)
    {
        _dbContextFactory = factory;
    }
    
    public IReadOnlyList<int> Seed(int numOrders)
    {
        using var db = _dbContextFactory.CreateDbContext();
    
        // Construct an in-memory dictionary pairing card SKUs to their database auto-incremented primary IDs.
        // This acts as a high-speed cache, preventing heavy relational JOIN or search lookups inside the loop.
        var pid = db.Cards.ToDictionary(c => c.Sku, c => c.Id);
    
        // Convert dictionary keys into a indexable string list so entries can be selected via numeric randomization
        var skusDisponibles = pid.Keys.ToList();
        int cantidadDeCartas = skusDisponibles.Count;
    
        List<int> ids = new();

        // Workload Construction Loop
        for (int i = 0; i < numOrders; i++)
        {
            // 1. Pick a random card SKU from our array layout index
            string skuAleatorio = skusDisponibles[Random.Shared.Next(0, cantidadDeCartas)];
            
            // 2. Fetch the corresponding real foreign key Integer ID directly from the dictionary cache
            int cardIdReal = pid[skuAleatorio];

            // Construct the root PurchaseOrder entity complete with a matching transactional OrderLine graph
            var order = new PurchaseOrder
            {
                // Assign a randomized Customer ID (Values 1, 2, or 3)
                CustomerId = Random.Shared.Next(1, 4), 
                Priority = (Random.Shared.Next(0, 2) == 0) ? OrderPriority.SpeedPlus : OrderPriority.Speed,
                Status = OrderStatus.Pending,
                CreatedAt = DateTime.UtcNow,
            
                // Instantiating the relational line item collections mapping to our selected card entity
                OrderLines = new List<OrderLine> 
                { 
                    new OrderLine 
                    { 
                        CardId = cardIdReal, 
                        Quantity = 1 
                    } 
                }
            };
        
            // Stage the entity hierarchy inside the operational DbContext. No database network traffic is made yet.
            db.Orders.Add(order);
        }
        
        // Push all staged changes down to the database engine in a single batched transactional write operation.
        db.SaveChanges();
    
        // Optimization Detail: After executing SaveChanges, the local tracking engine (ChangeTracker)
        // automatically intercepts the autogenerated sequence primary keys injected back by SQL server.
        // We traverse the state tracker directly to gather the fresh IDs without initiating a separate SELECT query.
        foreach (var entry in db.ChangeTracker.Entries<PurchaseOrder>())
        {
            ids.Add(entry.Entity.Id);
        }
    
        return ids;
    }
}